spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  default-chat-id: ${TELEGRAM_CHAT_ID}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

rate-limit:
  daily-messages: 100

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    com.notificationhub: INFO